name: Security Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 2

      - name: Run ClaudeCode Security Review
        id: claudecode
        uses: anthropics/claude-code-security-review@main
        with:
          comment-pr: true
          claude-api-key: ${{ secrets.CLAUDE_API_KEY }}

      - name: Upload ClaudeCode Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: claudecode-results
          path: claudecode-results.json
          if-no-files-found: warn
