name: Security Review

permissions:
  pull-requests: write
  contents: read

on:
  pull_request:
    branches:
      - main   

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 2
      
      - uses: anthropics/claude-code-security-review@main
        with:
          comment-pr: true
          claude-api-key: "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"
